# To find the class, just type 'hyprctl clients' with the opened required app, the list of the opened app will be displayed.
# Telegram
windowrule = float on, size 400 600, match:class org.telegram.desktop
# Terminal
windowrule = float on, match:class com.mitchellh.ghostty
# windowrule = size 400 600, class:com.mitchellh.ghostty
# File Manager
windowrule = float on, match:class org.gnome.Nautilus
# windowrule = size 400 600, class:com.mitchellh.ghostty
windowrule = float on, size 1000 800, match:class com.rafaelmardojai.Blanket
windowrule = float on, size 750 750, match:class org.gnome.Calendar
windowrule = float on, size 750 750, match:class org.gnome.clocks
