# To find the class, just type 'hyprctl clients' with the opened required app, the list of the opened app will be displayed.
# Telegram
windowrule = float, class:org.telegram.desktop
windowrule = size 400 600, class:org.telegram.desktop
# Terminal
windowrule = float, class:com.mitchellh.ghostty
# windowrule = size 400 600, class:com.mitchellh.ghostty
# File Manager
windowrule = float, class:org.gnome.Nautilus
# windowrule = size 400 600, class:com.mitchellh.ghostty
windowrule = float, class:com.rafaelmardojai.Blanket
windowrule = size 1000 800, class:com.rafaelmardojai.Blanket
windowrule = float, class:org.gnome.Calendar
windowrule = size 750 750, class:org.gnome.Calendar
windowrule = float, class:org.gnome.clocks
windowrule = size 750 750, class:org.gnome.clocks
